### ISSUE TITLE
Firmware 3.0.0 - TZ88E - Not Working 

### ISSUE THREAD

**Issue by wotojohn** [pshotton/com.tkbhome#1]
Since the new update all 3 of the TZ88E are not working - comes up with this error ‘ Could not get by device id ‘  all my other 5 switches work fine it’s only the 88 ones that don’t work

**Comment by pshotton** [comment]
I take it you're using the TZ88 driver. Can you create a diagnostics report and pm me the id. Thanks

**Comment by wotojohn** [comment]
Hi - Not sure if you can DM in Git - the switch has been working fine until the update - I did post it on the forum https://community.homey.app/t/tkb-home-firmware-3-0-0-problem/80151

**Comment by wotojohn** [comment]
Here is the Log file a0e4543f-9f82-4326-97d6-72e0729fb39f 

thanks

**Comment by pshotton** [comment]
That's brilliant, many thanks. I've just pushed a fix for this - let me know if it works.

**Comment by wotojohn** [comment]
Hi 
it’s coming up with this now 


![IMG_0737](https://github.com/pshotton/com.tkbhome/assets/132500604/6f9098d6-b481-4c4b-a9e9-b782a64711b2)



![IMG_0736](https://github.com/pshotton/com.tkbhome/assets/132500604/d6a71b76-d57c-4a4c-adcf-9468dda61645)

**Comment by pshotton** [comment]
Ah, that's an old invalid flow. Removed and pushed the new version. Let me know...

**Comment by johnwoto** [comment]
it's fixed - thank you for all your help
