### ISSUE TITLE
TZ78 In-Wall Single Relay Switch 

### ISSUE THREAD

**Issue by magpern** [pshotton/com.tkbhome#4]
**UPDATE: I will implement this and create a pull request**

**UPDATE 2: I have made all implementation. Struggeling with test environment**

**UPDATE 3: Tested. Works. Pull request created**

Could you add this device?
I have this device. I can be a beta tester.

Open-zwave have this
https://github.com/OpenZWave/open-zwave/blob/master/config/wenzhou/tz78.xml
(which by the way is me that implemented, I had forgot about it, but i see my name in the Author tag magpern)

Device data I found here
https://devices.zwave-js.io/?jumpTo=0x0118:0x0003:0x0005:0.0

or here
https://github.com/openhab/org.openhab.binding.zwave/blob/main/doc/tkb/tz78_0_0.md

and perhaps the best here
https://opensmarthouse.org/zwavedatabase/160

Maybe this helps. It is from zwave2mqtt.
Functions that are important (aside from just on/off) are
Memory function and Edge/pulse mode
and if you should be able to turn it off or not.

![image](https://github.com/pshotton/com.tkbhome/assets/6589760/e6ab56b0-9046-43e9-8977-e03f902903d6)
![image](https://github.com/pshotton/com.tkbhome/assets/6589760/dfe3efe4-fc15-45a6-a97b-188899041a7c)
![image](https://github.com/pshotton/com.tkbhome/assets/6589760/ac17b4b5-6428-4fdb-ba98-0396fc7eb8ff)
![image](https://github.com/pshotton/com.tkbhome/assets/6589760/f0daee2c-2157-4f89-8d13-98dbb459c883)

**Comment by pshotton** [comment]
@magpern Thank you very much. I've merged your changes. I'll do a build and push the new version later today.

**Comment by pshotton** [comment]
Pushed to Homey for certification. Available from store as test version
