### ISSUE TITLE
Tz75 roler shutter 

### ISSUE THREAD

**Issue by Tomasz325752** [pshotton/com.tkbhome#7]
Good morning, I would like to ask if you will support the TZ 75

**Comment by pshotton** [comment]
Hi. Closing this as there is already a open issue for the TZ75. When I get a moment I'll look into supporting.

**Comment by pshotton** [comment]
Hi. Closing this as there is already a open issue for the TZ75. When I get a moment I'll look into supporting.

**Comment by pshotton** [comment]
See https://github.com/pshotton/com.tkbhome/issues/3
